version: '3'

services:

  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

  redis:
    image: redis:latest

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ai_content
    ports:
      - "5432:5432"